### ISSUE TITLE
Revise and document projection matrix methods

### ISSUE THREAD

**Issue by juanjp600** [juanjp600/pge#25]

**Comment by Saalvage** [comment]
Investigate potentially broken clipping planes

**Comment by Saalvage** [comment]
Consider notes on D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/d3dcompile-constants

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/juanjp600/pge/commit/8d84736b6d416c1245f51b8e09136b8033885d98, may need some more testing.

**Comment by juanjp600** [comment]
Merged into main, theoretically this is done now
